name: Run PHPUnit Tests

on:
  push:
    branches:
      - main  # ou la branche sur laquelle vous souhaitez exécuter les tests
  pull_request:
    branches:
      - main  # ou la branche sur laquelle vous souhaitez exécuter les tests

jobs:
  phpunit:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu pour exécuter le test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Clone le code source du dépôt

      - name: Set up PHP
        uses: shivammathur/setup-php@v4 # Installe PHP
        with:
          php-version: '.2.12 '  # Indique la version de PHP que vous utilisez

      - name: Install dependencies
        run: |
          sudo apt-get install -y libxml2-dev
          composer install --no-interaction  # Installe les dépendances via Composer

      - name: Run PHPUnit tests
        run: |
          ./vendor/bin/phpunit --configuration phpunit.xml.dist  # Exécute PHPUnit avec votre fichier de configuration
