name: Run PHPUnit Tests

on:
  push:
    branches:
      - main  # ou la branche sur laquelle vous souhaitez exécuter les tests
      - hatim
  pull_request:
    branches:
      - main  # ou la branche sur laquelle vous souhaitez exécuter les tests
      - hatim

jobs:
  phpunit:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu pour exécuter le test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Clone le code source du dépôt

      - name: Set up PHP
        uses: shivammathur/setup-php@v2  # Utilisation de la version stable v2
        with:
          php-version: '8.2'  # Version de PHP (corrigée pour enlever l'espace supplémentaire)
          extensions: mbstring, xml, curl  # Si vous avez besoin d'extensions spécifiques, ajoutez-les ici
          coverage: xdebug  # Active la couverture de code (si vous en avez besoin)

      - name: Install dependencies
        run: |
          sudo apt-get install -y libxml2-dev
          composer install --no-interaction  # Installe les dépendances via Composer

      - name: Run PHPUnit tests
        run: |
          ./vendor/bin/phpunit --configuration phpunit.xml.dist  # Exécute PHPUnit avec votre fichier de configuration
